[build]
  command = "npm run dev"  
  publish = "client/build"                  

[build.environment]
  NODE_VERSION = "14"  

[[redirects]]
  from = "/*"          
  to = "/index.html"
  status = 200
