[build]
  command = "npm run build --prefix client"  
  publish = "client/build"                  

[build.environment]
  NODE_VERSION = "20.15.1"  

[[redirects]]
  from = "/*"          
  to = "/index.html"
  status = 200
